### ISSUE TITLE
Zoom from share link is resetting

### ISSUE THREAD

**Issue by Fank** [OCAP2/web#15]
http://162.55.178.211:5000/?file=2021_07_10__02_16_opt_v41.json&frame=0&zoom=6.300000000000001&x=-140.09450120591094&y=112.15428791562577

If you click on this link you can see in beginning its trying ot zoom in as i shared it, but right after that it resets the zoom and you can see the whole map.
This is something i haven't see before the marker changes.

**Comment by indig0fox** [comment]
in OCAP.js search map.fitBounds(), likely what is defaulting to zoom of whole map and not respecting share link entry.
